### ISSUE TITLE
@notifications only happen when people /d request

### ISSUE THREAD

**Issue by raysun** [raysun/Clash-of-Clans-Notifier#11]
made this change to reduce over-notifications. but is that always correct? should this be an option?

**Comment by xDp64xG** [comment]
Leave an option to change between the 2 settings, overload notifications, to minimum

**Comment by raysun** [comment]
yep, that's probably the best option

**Comment by raysun** [comment]
what's good about the /d only is that it effectively turns it off during wars, without anyone having to /off the bot. since donations aren't urgent. at the same time, when the bot is introduced to a new clan, no one gets notifications since they don't know /d yet, and so they don't learn the feature. it's an interesting q.
