### ISSUE TITLE
/d requests always go to @everyone

### ISSUE THREAD

**Issue by raysun** [raysun/Clash-of-Clans-Notifier#12]
in large clans, this is too noisy. who should it target? everyone that has the troop? everyone that has higher level troops? some heuristic that balances "historical time it takes to donate" with "level of troop?"

**Comment by xDp64xG** [comment]
Target the people with the high lvl troops, from high to -1 high? Ex: /d wiz - (looks up with highest lvl wiz,(5)) Alerts people with lvl 5 wiz, and lvl 4, or have /d Wiz <lvl> to specify?

**Comment by raysun** [comment]
yep, /d wiz level 5, or some variant of that, is the most explicit & predictable command
