### ISSUE TITLE
Troop Wiki and stats

### ISSUE THREAD

**Issue by redsk1ns** [raysun/Clash-of-Clans-Notifier#15]
Custom commands from another bot as an example

![image](https://cloud.githubusercontent.com/assets/24313226/22192172/a9a3f04e-e0ff-11e6-9584-89fe9be1e0b6.png)

![image](https://cloud.githubusercontent.com/assets/24313226/22192184/c2d33bce-e0ff-11e6-89bc-50f1dab70e23.png)

**Comment by xDp64xG** [comment]
The first part seems like it should not be added, but the stats is a must. So have an array of Level 1 archers = Dps,Hp,Training_Cost,Research_Cost,Lab_Required,Research_Time
Which would have to be hard coded into the actual program, unless @raysun is able to pick it from the website. But information about the archer proves to be irrelevant as we are intending for stats.
