### ISSUE TITLE
war troop calculator actually redownloads the clan info instead of using the cached clan data

### ISSUE THREAD

**Issue by raysun** [raysun/Clash-of-Clans-Notifier#9]
no reason, just legacy. can be fixed by saving achievement info during the main data download loop

**Comment by xDp64xG** [comment]
so then have a command that re downloads everything? Have the loop removed in exchange for the command, and only a select few are able to do that, that in mind, moderators are only allowed to do all commands besides /d? And pending war bases.

**Comment by raysun** [comment]
Thanks, sorry this is just an implementation bug that I'm using for tracking. war troop calculations should be instant, but right now force a full redownload from the server.
